#!/bin/bash 

declare -A COUNTER
COUNTER[5301d1]='MEM_LOAD_UOPS_RETIRED.L1_HIT '
COUNTER[5302d1]='MEM_LOAD_UOPS_RETIRED.L2_HIT '
COUNTER[5304d1]='MEM_LOAD_UOPS_RETIRED.L3_HIT '
COUNTER[5308d1]='MEM_LOAD_UOPS_RETIRED.L1_MISS'
COUNTER[5310d1]='MEM_LOAD_UOPS_RETIRED.L2_MISS'
COUNTER[5320d1]='MEM_LOAD_UOPS_RETIRED.L3_MISS'
COUNTER[5340d1]='MEM_LOAD_UOPS_RETIRED.HIT_LFB'
COUNTER[5308f0]='L2_TRANS.ALL_PF              '
COUNTER[53f824]='L2_RQSTS.ALL_PF              '
COUNTER[533824]='L2_RQSTS.PF_MISS             '
COUNTER[53d824]='L2_RQSTS.PF_HIT              '
COUNTER[53e124]='L2_RQSTS.ALL_DEMAND_DATA_RD  '

if [[ -z "$1" || -z "$2" || -z "$3" || -z "$4" ]]; then
  echo 'Usage: count N TSI TSJ TSK'
  exit 1;
fi

make -B OPTS='-O3 -no-vec' DEFS="-DTI=$2 -DTJ=$3 -DTK=$4" > /dev/null 2>&1;

cmd="perf stat -e r5301d1,r5302d1,r5304d1,r5340d1,r53d824,r5308f0,r53f824,r53e124,r5308d1,r5310d1,r5320d1,r533824 ./MM $1"
cmd="perf stat -r 3 -e r5301d1,r5302d1,r5340d1,r53d824,r53f824,r53e124,r5308d1,r5310d1,r533824 ./MM $1"
echo "$cmd (TI=$2 TJ=$3 TK=$4)"

lines="$(${cmd} 2>&1 | sed "s~\(.*r\)\(.*\):u[ ]\+\(.*\)~\1\2 - \${COUNTER[\2]}  \3~")"
eval "echo \"$lines\""

