#!/bin/bash 

declare -A COUNTER
COUNTER[5308b0]='OFFCORES_REQUESTS.ALL_DATA_RD '

if [[ -z "$1" || -z "$2" || -z "$3" || -z "$4" ]]; then
  echo 'Usage: count N PI PJ TK'
  exit 1;
fi

echo "./MM $1 (PI=$2 PJ=$3 TK=$4)"

cmd="perf stat -r 10 -e r5308b0 ./MM $1 $2 $3 $4"
lines="$(${cmd} 2>&1 | sed "s~\(.*r\)\(.*\):u[ ]\+\(.*\)~\1\2 - \${COUNTER[\2]}  \3~")"
eval "echo \"$lines\""

